// GENERATED by scripts/emu_desc.py oracle — do not edit.
// Each vector is the sha256 of the full 0x120 descriptor block that
// the engine's OWN writers (0x1D15270 static, 0x1D152D0 dynamic) produce
// for (id, name) at slot=0x50000000, module base=0x140000000.
// One vector per distinct name length in the 9,863-entry table, plus every
// name of length >= 60, plus add_modifier.

pub const slot: usize = 0x50000000;
pub const module_base: usize = 0x140000000;

pub const Vector = struct { id: u32, name: []const u8, sha256: []const u8 };

pub const vectors = [_]Vector{
    .{ .id = 11, .name = "id", .sha256 = "e9c9ec5c4da1dac29c429d11f696187259298f79e84cb7a6465e657c57253763" },
    .{ .id = 21, .name = "idtype", .sha256 = "6a59c1f7923c1dd6485476f4600837f296e83214e78dbf1f202c78d673d135e4" },
    .{ .id = 22, .name = "machineid", .sha256 = "ee90f91a9e7e4e2415e31d3f68e8599ed615e7dbe8cda178d7e9a8dfd0af18ea" },
    .{ .id = 24, .name = "filelist", .sha256 = "e8f61ce70dc6afdfcb288ffa854a9e7da2be717aa95546e91ad7320623d0cea2" },
    .{ .id = 25, .name = "dir", .sha256 = "e69db0dc61dd6a6bc666bdb32cf04ea7f1edf3ea8d40196347b5bc5133e1ab27" },
    .{ .id = 26, .name = "file", .sha256 = "2da89de0d4dc4d873a46f5f23db0542d4e1bfa35d95c1830430776ac742f1421" },
    .{ .id = 28, .name = "noOfFrames", .sha256 = "d78a2f246e9914b117d0993b8d37fdffb7b351f8f9dbb04dd07de2c2887a3ead" },
    .{ .id = 29, .name = "fonts", .sha256 = "0ccdd05bae6bb7feac95c27b6870a3e16ecd0cbbaf528d2295f62f186ff54042" },
    .{ .id = 32, .name = "x", .sha256 = "ee6d9162ab68cb285f03da50f6e2e5a0887c234007332de57a1cfefa84abb48b" },
    .{ .id = 35, .name = "charSet", .sha256 = "adc6720e97789bd56f2336837885b28d4f7a898c63f080f61111176ee33fabc2" },
    .{ .id = 37, .name = "textureFile", .sha256 = "cd141a699502262f651377821f89dd20660dfc4058493839378f49492440a31a" },
    .{ .id = 38, .name = "textureFile1", .sha256 = "f3ae5881e9a0eec3408aa29033fa5aa6167e16cec13770cedc3db31f46875213" },
    .{ .id = 59, .name = "animatedMeshType", .sha256 = "67c9843d989995cb524345b4fb5a46fb743c8417599ec513dc4ef22395ce504d" },
    .{ .id = 66, .name = "defaultAnimationTime", .sha256 = "4e1e67949154a9dafa732917d971d53bc78c3bf50acc7dc4d1b4c8541e186ef2" },
    .{ .id = 71, .name = "textSpriteType", .sha256 = "5a28f9e7b405cdbd1f836272048292f8dc0f617d33792e9fdee2509993bf3430" },
    .{ .id = 85, .name = "corneredTileSpriteType", .sha256 = "4878b9e54cf6dbe15cd5e7c79266dee45a4b3787657d0c5cf77dcfd23648c431" },
    .{ .id = 91, .name = "primitiveType", .sha256 = "e84c370576f577d926430c1c425461b412e5ca86016e12074597e6f270fd7228" },
    .{ .id = 111, .name = "anti_alias_geometry", .sha256 = "e673b02b9ca702c8a6df09f20af35cc0aea7aefd1d7c1cf2c51a51c0682d6d6b" },
    .{ .id = 168, .name = "listBoxItemType", .sha256 = "2d699038169d1602d37ca786db0177239c573fc2052c80245c74fcc72a001385" },
    .{ .id = 750, .name = "scrollbaralign_vertical", .sha256 = "230734dac45de9e4fa6ea9b2fbad19c91ff7ea0efedae2613b1f5b59afa9dab0" },
    .{ .id = 751, .name = "scrollbaralign_horizontal", .sha256 = "569e41078e4e891d3964742fdbd1e598dba2d9c1f101d030c5f006d679c59dc5" },
    .{ .id = 782, .name = "looping_delay_random_offset", .sha256 = "e8be305ac911abeb05c07d240ea6fe77ad9920c38c4754885a0cdafaa4aa7c25" },
    .{ .id = 793, .name = "looping_playbackrate_random_offset", .sha256 = "0b05524f9bc02d546ae5207559aae1f22cf5d6e0f6662a001b34cb1743bd88aa" },
    .{ .id = 809, .name = "layoutstretchfactor_horizontal", .sha256 = "5122d2221c47dc46b14962d530a84c9adb09e5249ab896acf8fe8dde82c7a6cd" },
    .{ .id = 810, .name = "layoutstretchfactor_vertical", .sha256 = "bd3eb83b590a1dbea00b1069ab2258a60e4a901faf8a78d17a40f2ec55276ba2" },
    .{ .id = 991, .name = "additive_animation", .sha256 = "6dbcffdf7d2a4167e91883537754d659880fe18cf36d3a430f48a6f99c78244c" },
    .{ .id = 1049, .name = "sprite_sheet_sprite_type", .sha256 = "c95fc9d6335aa02bf4fe17c287472e21c22d21159c568dc8c3567b51093b2dfd" },
    .{ .id = 1075, .name = "flowmap_intensity", .sha256 = "7468960d7583de3ab497046d1a2d1c6aaf97a69713f03ba63b1642973c367a9a" },
    .{ .id = 1200, .name = "spritesheet_animation", .sha256 = "31dbd7f7e5254776dfdbc2e1e7a2f3fab64b4d510b80681e1fc37f496780d252" },
    .{ .id = 1201, .name = "spritesheet_animation_loop", .sha256 = "6d339e358c611370b714a0b6fc6056d5e5ba43ef49809f4fea34dc4ec48df724" },
    .{ .id = 10019, .name = "validate_and_repair_planet_buildings_and_districts", .sha256 = "d6ceabdc97d3fc442541b24308e26ed1840c8b1a68ada8f1cd17e08e3dfe1c08" },
    .{ .id = 10104, .name = "add_modifier", .sha256 = "f047ff311a243bbd6d5ee7f570ea83118dd1f9690c13679beb056f6c1428c604" },
    .{ .id = 10121, .name = "export_modifier_duration_to_variable", .sha256 = "bc7993830b847bf9efba121391aa547c579fed0288382f5c713d45f15372ec4d" },
    .{ .id = 10122, .name = "export_trigger_value_to_variable", .sha256 = "63901ccf1e27308fe46303f47195d29fc97d0be568d5f6e9055663e9fd7ab918" },
    .{ .id = 10123, .name = "export_resource_stockpile_to_variable", .sha256 = "f0dc493feb0518fc71a645adf17296b7c2c4a761b91d9ef6b3ad8c1830bc7df4" },
    .{ .id = 10125, .name = "export_resource_maximum_to_variable", .sha256 = "473612784b2bbcb715d008b41be059a43a8a559a844691fb65919f15b4227486" },
    .{ .id = 10166, .name = "unlock_random_tech_group_tech", .sha256 = "9e70a0fbb0a407d18f08fdede6cde3472996e77f3fd9f332b4c0b0daea8a454b" },
    .{ .id = 10560, .name = "set_espionage_operation_progress_locked", .sha256 = "394c6aea0195e75894d903dfd9fcdb3722114ae1191c59ebba2c465159a1462e" },
    .{ .id = 10566, .name = "remove_espionage_operation_flag", .sha256 = "e00dac90e72a0552bc100e4e5ab582cfb97dfb2676f1a2b6e65ec5f3b3429ad9" },
    .{ .id = 10583, .name = "store_galactic_community_leader_backup_data", .sha256 = "6726d28022641d20a95609a89ef23f3300db8b054d471e9fc3cde255e7cd2fe2" },
    .{ .id = 10584, .name = "restore_galactic_community_leader_backup_data", .sha256 = "3a095bd26cf0e2db49095354827c498bc15899dd8cd4c6dc78b8bb08483342c9" },
    .{ .id = 10600, .name = "set_rule_can_subject_do_diplomacy", .sha256 = "acb6505b14a5f05c2fdd5efd2ad0fc5e78c9abf77e5d25d867e9dc24e7813199" },
    .{ .id = 10665, .name = "remove_from_cosmic_storm_influence_field", .sha256 = "01fbc6d7711bc2d9bd073d83d2cd73dd9dad05e3bb31c24a56811c05036ef2db" },
    .{ .id = 10784, .name = "planet_max_branch_office_buildings_add", .sha256 = "63ff24d05c645db89d554da36a3a3d2561ff499fd9c8da0a490d797374251078" },
    .{ .id = 10875, .name = "should_ai_build_stronghold_on_vulnerable_colony", .sha256 = "d2c5ba0ed95e412423fc4498cf0128e2d3f3ef9621c40de48adec833e6dc1586" },
    .{ .id = 10935, .name = "ship_orbital_bombardment_army_damage_mult", .sha256 = "855ed0d03388462d3b4f8d0b350de17257bb89d4c5b09129e2b218835a62eee2" },
    .{ .id = 10948, .name = "branch_office_criminal_syndicate_value_add", .sha256 = "493d28fdabeb963440c836e8c83b9098e43d63a46357af7dc61140a090fb7208" },
    .{ .id = 11190, .name = "change_job_automated_workforce_limit_command", .sha256 = "7a748c9be15e9e16ae1c3cab561b2621d37a1325c05916d18d2d1942104bc032" },
    .{ .id = 11236, .name = "change_buildable_planet_queue_priority_command", .sha256 = "c88ad653ff46e1da75b8642dc861ba6086e60673ed62b9df262b303f197fb325" },
    .{ .id = 13100, .name = "ship_anomaly_generation_chance_mult_uninhabitable", .sha256 = "ac8cbbca8b160b643d2329f7cd0f01e9f358f35831dfeaa00f089373a908596e" },
    .{ .id = 13884, .name = "should_remove_response_message_when_not_possible", .sha256 = "8ba8910c18f4d90d7b941d512e9c10571622afb7fdafe5ce5c26d75c3cb92589" },
    .{ .id = 13946, .name = "country_federation_fleet_contribution_naval_cap_reduction_discount", .sha256 = "30543592e1957716b4692879cd3c683ca18cdf8af09fd9d4f1c1ab6dcb659491" },
    .{ .id = 14326, .name = "mod_distance_to_capital_static_modifier_efficiency_mult", .sha256 = "010a2b0e861fad967b0e403fd63ad6fc4c61fc2df4300a84b123ff30486d4988" },
    .{ .id = 14517, .name = "country_naval_capacity_contribution_from_subjects_mult", .sha256 = "29a7be569e5d7c839138ee1e829bb74ee0a19b5e27fe07578a8032e8bf7ba04a" },
    .{ .id = 14518, .name = "country_naval_capacity_contribution_to_overlord_mult", .sha256 = "cd88d4eaf12f1113865408fcf3a8540b70abae1cb4b038b572dd9e294f57422f" },
    .{ .id = 18721, .name = "num_cosmic_storm_late_game_spawn_chance_scale_setting", .sha256 = "a617d38bfaea141895bb201b5cf7ebd8ca72357e44112921ae415869cc286b6d" },
};
